<template>
	<header>
		<VRow>
			<VCol>
				<div class="flex items-center gap-4">
					<WebPExpressLogo class="h-12" />
					<h2 class="font-bold text-2xl">WebP Express</h2>
				</div>
			</VCol>
			<VCol align="right">
				<ModuleExternalLink href="https://github.com/rosell-dk/webp-express?tab=readme-ov-file" />
			</VCol>
		</VRow>
	</header>
	<main>
		<VRow>
			<VCol>
				<ModuleStatus :enabled="isEnabled" />
				<div class="prose">
					<p>
						More than 9/10 users are using a browser that is able to display webp images. Yet, on most
						websites, they are served jpeg images, which are typically double the size of webp images for a
						given quality. What a waste of bandwidth!
					</p>
					<p>
						This plugin was created to help remedy that situation. With little effort, Wordpress admins can
						have their site serving autogenerated webp images to browsers that support the format, while
						still serving jpeg and png files to browsers that do not.
					</p>
					<h2 class="text-xl mt-0">Module Features</h2>
					<ul>
						<li>Automated setup of required WebP Express settings (see below)</li>
						<li>Modifies any calls to <code>ImageResource</code> to replace all URLs with .webp URLS.</li>
					</ul>
				</div>
				<VAlert class="max-w-prose mt-4" type="warning">
					<p>
						This module relies on all of your images having already-converted .webp versions available.
						Ensure you're using the recommended config and have bulk-converted any existing images before
						use.
					</p>
				</VAlert>
			</VCol>
			<VCol>
				<DocumentationLink href="https://inertia-wordpress.evomark.co.uk/modules/webp-express">
					WebP Express
				</DocumentationLink>
				<h2 class="text-xl mt-4 mb-2 font-bold">Settings</h2>
				<VTable v-if="config" class="not-prose" density="comfortable">
					<thead>
						<tr class="bg-teal-500 text-white">
							<th>Setting</th>
							<th>Value</th>
							<th>Is Recommended?</th>
						</tr>
					</thead>
					<tbody>
						<tr v-for="(value, key) in relevantConfig">
							<td>{{ key }}</td>
							<td>{{ resolveRecommendedValue(value, key) }}</td>
							<td class="text-center">
								<VIcon
									v-if="checkIfUsingRecommended(key, value)"
									color="success"
									:icon="mdiCheckCircleOutline"
								/>
								<VIcon v-else color="error" :icon="mdiCloseCircleOutline" />
							</td>
						</tr>
					</tbody>
				</VTable>
				<VSkeletonLoader v-else type="table-heading, table-tbody"></VSkeletonLoader>
				<div class="flex justify-end">
					<VBtn
						class="mt-4"
						color="success"
						:loading="isUpdating"
						:disabled="isUsingRecommended"
						@click="onConfigurationSetup"
						>Use Recommended Configuration</VBtn
					>
				</div>
			</VCol>
		</VRow>
	</main>
	<footer class="mt-4">
		<BackToSettingsLink />
	</footer>
	<v-snackbar v-model="showSnackbar" color="success">
		Your WebP Express configuration has been set to the recommended
	</v-snackbar>
</template>

<script setup>
import ModuleStatus from "components/ModuleStatus.vue";
import ModuleExternalLink from "components/ModuleExternalLink.vue";
import WebPExpressLogo from "components/WebPExpressLogo.vue";
import BackToSettingsLink from "components/BackToSettingsLink.vue";
import DocumentationLink from "components/DocumentationLink.vue";
import { useSettings } from "composables/useSettings";
import { useApi } from "composables/useApi";
import { computed, ref } from "vue";
import { pick } from "lodash-es";
import { mdiCheckCircleOutline, mdiCloseCircleOutline } from "@mdi/js";

const api = useApi();
const { settings } = useSettings(["modules"]);
const isEnabled = computed(() => settings.value?.modules && settings.value.modules.includes("webp-express"));

const config = ref(null);
const relevantConfig = computed(() =>
	pick(config.value, [
		"operation-mode",
		"destination-extension",
		"enable-logging",
		"prevent-using-webps-larger-than-original",
		"convert-on-upload",
		"alter-html",
		"web-service",
	]),
);
const recommendedConfig = {
	"operation-mode": "cdn-friendly",
	"destination-extension": "append",
	"enable-logging": false,
	"prevent-using-webps-larger-than-original": true,
	"convert-on-upload": true,
	"alter-html": (value) => {
		return value.enabled === false;
	},
	"web-service": (value) => {
		return value.enabled === false;
	},
};
const isUsingRecommended = computed(() => {
	if (!config.value) return false;

	return Object.entries(recommendedConfig).every(([key, value]) => {
		return config.value[key] === value;
	});
});

api.get("modules/webp-express/configuration").then((res) => {
	if (res.success === true) {
		config.value = res.data.config;
	}
});

const isUpdating = ref(false);
const showSnackbar = ref(false);
const onConfigurationSetup = () => {
	isUpdating.value = true;
	api.post("modules/webp-express/configuration")
		.then((res) => {
			if (res.success === true) {
				config.value = res.data.config;
				showSnackbar.value = true;
			}
		})
		.finally(() => {
			isUpdating.value = false;
		});
};

const checkIfUsingRecommended = (key, value) => {
	const recommended = recommendedConfig[key];
	if (typeof recommended !== "function") {
		return value === recommended;
	} else {
		return recommended(value);
	}
};

const resolveRecommendedValue = (value, key) => {
	switch (key) {
		case "alter-html":
		case "web-service":
			return value.enabled;
		default:
			return value;
	}
};
</script>
